<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/a_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor
- array, matrix와 매우 유사한 특수한 자료구조
- PyTorch에서는 모델의 입력과 출력 매개변수들을 텐서를 이용해 encode 한다.
- GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 Numpy ndarray와 유사하다.

In [1]:
import torch
import numpy as np

# Tensor Initialize
- 데이터로부터 텐서 직접 생성
- 데이터의 자료형은 자동으로 유추한다.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_data

tensor([[1, 2],
        [3, 4]])

- Numpy 배열로 부터 텐서를 생성할 수도 있다.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

- 다른 텐서에서 재정의해보기 (Override)
- shape, datatype을 유지한다. (주어진 텐서 속성 유지)

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor : \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor : \n{x_rand} \n")

Ones Tensor : 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
tensor([[0.3565, 0.7254],
        [0.7350, 0.7244]]) 



- **random** or **constant** 값 사용하기

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor} \n")

Random Tensor : 
 tensor([[0.2383, 0.8180, 0.4003],
        [0.5487, 0.8058, 0.1006]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# Tensor Attribute
- shape, datatype 및 어느 장치에 저장되는지를 나타낼 수 있다.

In [8]:
shape = (3, 4)
tensor = torch.rand(shape)

print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


# Tensor Operation
- transposing(전치), Indexing, Slicing, Calculate, 선형 대수, random sampling ..
  - 100가지 이상의 텐서 연산
  - https://pytorch.org/docs/stable/torch.html
- 기본적으로 텐서는 CPU에서 생성
- .to 메소드 사용 시 GPU로 텐서를 명시적으로 이동 할 수 있다.
  - 장치 간 큰 텐서를 복사하는 것은 시간과 메모리 측면 비용이 많이든다는 것에 주의 

In [9]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [11]:
tensor.device

device(type='cuda', index=0)

- Numpy식 표준 인덱싱과 슬라이싱 가능하다.

In [18]:
tensor = torch.ones(4, 4)
print(f"tensor : \n : {tensor} \n")
print("First row : ", tensor[0])
print("First column : ", tensor[:, 0])
print("Last column : ", tensor[..., -1])
print()
tensor[:, 1] = 0 # 1 index의 Column을 싹 0으로 바꾼다.
print(f"tensor : \n : {tensor} \n")

tensor : 
 : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

First row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])

tensor : 
 : tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



- **텐서 합치기**, torch.cat을 사용한다.
- **주어진 차원에 따라** 일련의 텐서를 연결할 수 있다.

In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


- matrix multiplication(행렬곱)

In [23]:
# 행렬곱 수행하는 3가지 방법

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y1 :{y1}")
print(f"y2 :{y2}")
print(f"y3 :{y3}")

y1 :tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 :tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 :tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


- single-element tensor
- 텐서의 모든 값을 하나로 집계(aggregate) 해서 **요소가 하나인 텐서의 경우** item()을 사용해 Python 숫자 값으로 변환할 수 있다.

In [28]:
agg = tensor.sum()
agg_item = agg.item()
print(f"tensor : \n {tensor} \n")
print(agg_item, type(agg_item))

tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

12.0 <class 'float'>


- In-place 연산 : 바꿔치기 연산
- 연산결과를 피연산자(Operand)에 저장하는 연산
- '_' 접미사를 갖는다.
  - x.copy_(y) or x.t_()
- 메모리를 일부 절약한다.
- 하지만 도함수 계산에 문제가 발생할 수 있어 권장하지 않는다.
  - history가 즉시 삭제됨(원래 값)


In [29]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


 # Numpy 변환 (Bridge)
 - CPU 상 텐서와 Numpy 배열은 메모리 공간을 공유
 - 하나를 변경하면 다른 하나도 변경된다.

In [31]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [32]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
t.add_(1)
t

tensor([2., 2., 2., 2., 2.])

In [35]:
n # tensor의 변경사항이 Numpy 배열에 반영된다. **메모리 공유 !**

array([2., 2., 2., 2., 2.], dtype=float32)

- Numpy 배열을 Tensor로 변환 가능하다.

In [39]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [40]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [41]:
np.add(n, 1, out=n)
n

array([2., 2., 2., 2., 2.])

In [43]:
t # 역시나 메모리 공유

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)