<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/b_TensorCompute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# vector
v = torch.tensor([1,2,3.])
w = torch.tensor([0, 10, 20])

# matrix
m = torch.tensor([ [0, 1, 2], [100, 200, 300.] ])

In [5]:
v2 = v + 10 # vector + scalar : 기본적으로 broadcasting을 한다.
v2

tensor([11., 12., 13.])

In [6]:
v2 = v ** 2 # 제곱
v2

tensor([1., 4., 9.])

In [8]:
z = v - w # 동일 길이 벡터간 뺄셈
z

tensor([  1.,  -8., -17.])

In [9]:
u = 2 * v - w / 10 + 6.0
u

tensor([ 8.,  9., 10.])

In [12]:
m2 = m * 2.0 # 행렬과 스칼라 곱 : 역시 기본적으로 broadcasting
m2

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])

In [13]:
m + v # 행렬 + vector : 역시 broadcasting

tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])

In [14]:
m + m # 행렬간 덧셈

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])