<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/c_TensorDimensionOper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x1 = torch.tensor([ [1, 2], [3, 4.] ]) # 2 x 2 Matrix
x2 = torch.tensor([ [10, 20, 30], [40, 50, 60.] ]) # 2 x 2 Matrix

In [3]:
x1.view(4, 1) # 2 x 2 -> 4 x 1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [4]:
x1.reshape(4, 1) # 2 x 2 -> 4 x 1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [5]:
x1.view(-1) # flatten, 1 dim vector

tensor([1., 2., 3., 4.])

In [6]:
x1.reshape(-1)

tensor([1., 2., 3., 4.])

In [7]:
x1.shape

torch.Size([2, 2])

In [8]:
x1.view(1, -1) # -1 사용시 shape에서 자동 계산이 가능한 부분에 한해서 자동 입력된다. (1, -1)을 넣었지만 (1, )이므로 그냥 (1, )로 처리됨

tensor([[1., 2., 3., 4.]])

In [9]:
x1.reshape(1, -1)

tensor([[1., 2., 3., 4.]])

In [10]:
print(f"x2 : \n\n {x2}\n")
print(f"x2 transposed : \n\n {x2.t()}") # transpose

x2 : 

 tensor([[10., 20., 30.],
        [40., 50., 60.]])

x2 transposed : 

 tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])


In [11]:
torch.cat([x1, x2], dim=1) # 행렬을 묶는 method

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [12]:
hwc_img_data = torch.rand(100, 64, 32 ,3)
hwc_img_data.shape

torch.Size([100, 64, 32, 3])

In [13]:
chw_img_data = hwc_img_data.transpose(1, 2) # 1 차원과 2차원을 교환  BHWC -> BWHC

In [14]:
chw_img_data = chw_img_data.transpose(1, 3) # 1 차원과 3차원의 값들을 교환 BWHC -> BCHW
chw_img_data.size()

torch.Size([100, 3, 64, 32])

# Squeezing
- dim 중 1로 되어있는 것을 압축한다.
  - 사실 불필요한 차원일 수 있기때문에 압축시키는 것이 필요할 수 있다. (그때 사용)
- torch.squeeze(input, dim)
  - dim 지정하지 않았을 시 : 차원이 1인 모든 차원을 압축

In [15]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size() # dim : 2, 1, 2, 1, 2 인 zeros matrix

torch.Size([2, 1, 2, 1, 2])

In [16]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [17]:
y = torch.squeeze(x, dim=0)
y.size() # 0번째 차원은 1이 아니므로 squeeze가 안된다.

torch.Size([2, 1, 2, 1, 2])

In [18]:
y = torch.squeeze(x, dim=1)
y.size()

torch.Size([2, 2, 1, 2])

- unsqueeze : dim을 추가할 수 있다. 정확히 반대의 기능을 수행한다.

In [19]:
x = torch.zeros(2, 3, 4)
x = torch.unsqueeze(x, 0) # 0번째 앞에 차원이 추가된다.
x.size()

torch.Size([1, 2, 3, 4])

In [20]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [21]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

# Transpose
- PyTorch에서 다루는 이미지 데이터 (c, h, w)
- OpenCV의 경우 (h, w, c)
- 순서 바꾸는게 필요하다.

In [22]:
import cv2
import numpy as np

In [23]:
A = np.ones((100, 120, 3))
A_transposed = np.transpose(A, (2, 0, 1))
A_transposed.shape # numpy 는 한번에 바꿔준다. (numpy 단에서는 이렇게 빨리 처리하는 것을 추천)

(3, 100, 120)

In [24]:
B = torch.Tensor(A)
B_transposed = torch.transpose(B, 1, 2)
B_transposed.shape

torch.Size([100, 3, 120])

In [27]:
B_transposed2 = torch.transpose(B_transposed, 0, 1)
B_transposed2.shape # 두번해야되니까 비효율적

torch.Size([3, 100, 120])

# Permute를 통한 shape 변경
- transpose는 1:1 dim 교환 방식이지만, permute를 사ㅛㅇ하면 채널 방향의 순서를 한번에 쉽게 바꿀 수 있다.

In [28]:
A = torch.ones(1, 3, 10, 20)
A.shape

torch.Size([1, 3, 10, 20])

In [29]:
A = A.permute(1, 3, 0, 2)
A.shape # 1차원 -> 0차원으로, 3 -> 1 , 0 -> 2, 2 -> 3

torch.Size([3, 20, 1, 10])