<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/c_TensorDimensionOper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x1 = torch.tensor([ [1, 2], [3, 4.] ]) # 2 x 2 Matrix
x2 = torch.tensor([ [10, 20, 30], [40, 50, 60.] ]) # 2 x 2 Matrix

In [3]:
x1.view(4, 1) # 2 x 2 -> 4 x 1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [4]:
x1.reshape(4, 1) # 2 x 2 -> 4 x 1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [5]:
x1.view(-1) # flatten, 1 dim vector

tensor([1., 2., 3., 4.])

In [6]:
x1.reshape(-1)

tensor([1., 2., 3., 4.])

In [7]:
x1.shape

torch.Size([2, 2])

In [8]:
x1.view(1, -1) # -1 사용시 shape에서 자동 계산이 가능한 부분에 한해서 자동 입력된다. (1, -1)을 넣었지만 (1, )이므로 그냥 (1, )로 처리됨

tensor([[1., 2., 3., 4.]])

In [9]:
x1.reshape(1, -1)

tensor([[1., 2., 3., 4.]])

In [10]:
print(f"x2 : \n\n {x2}\n")
print(f"x2 transposed : \n\n {x2.t()}") # transpose

x2 : 

 tensor([[10., 20., 30.],
        [40., 50., 60.]])

x2 transposed : 

 tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])


In [11]:
torch.cat([x1, x2], dim=1) # 행렬을 묶는 method

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [12]:
hwc_img_data = torch.rand(100, 64, 32 ,3)
hwc_img_data.shape

torch.Size([100, 64, 32, 3])

In [13]:
chw_img_data = hwc_img_data.transpose(1, 2) # 1 차원과 2차원을 교환  BHWC -> BWHC

In [14]:
chw_img_data = chw_img_data.transpose(1, 3) # 1 차원과 3차원의 값들을 교환 BWHC -> BCHW
chw_img_data.size()

torch.Size([100, 3, 64, 32])

# Squeezing
- dim 중 1로 되어있는 것을 압축한다.
  - 사실 불필요한 차원일 수 있기때문에 압축시키는 것이 필요할 수 있다. (그때 사용)
- torch.squeeze(input, dim)
  - dim 지정하지 않았을 시 : 차원이 1인 모든 차원을 압축

In [16]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size() # dim : 2, 1, 2, 1, 2 인 zeros matrix

torch.Size([2, 1, 2, 1, 2])

In [17]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [20]:
y = torch.squeeze(x, dim=0)
y.size() # 0번째 차원은 1이 아니므로 squeeze가 안된다.

torch.Size([2, 1, 2, 1, 2])

In [21]:
y = torch.squeeze(x, dim=1)
y.size()

torch.Size([2, 2, 1, 2])

- unsqueeze : dim을 추가할 수 있다. 정확히 반대의 기능을 수행한다.

In [24]:
x = torch.zeros(2, 3, 4)
x = torch.unsqueeze(x, 0) # 0번째 앞에 차원이 추가된다.
x.size()

torch.Size([1, 2, 3, 4])

In [25]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [26]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])