<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/c_TensorDimensionOper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x1 = torch.tensor([ [1, 2], [3, 4.] ]) # 2 x 2 Matrix
x2 = torch.tensor([ [10, 20, 30], [40, 50, 60.] ]) # 2 x 2 Matrix

In [4]:
x1.view(4, 1) # 2 x 2 -> 4 x 1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [5]:
x1.reshape(4, 1) # 2 x 2 -> 4 x 1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [7]:
x1.view(-1) # flatten, 1 dim vector

tensor([1., 2., 3., 4.])

In [9]:
x1.reshape(-1)

tensor([1., 2., 3., 4.])

In [18]:
x1.shape

torch.Size([2, 2])

In [12]:
x1.view(1, -1) # -1 사용시 shape에서 자동 계산이 가능한 부분에 한해서 자동 입력된다. (1, -1)을 넣었지만 (1, )이므로 그냥 (1, )로 처리됨

tensor([[1., 2., 3., 4.]])

In [13]:
x1.reshape(1, -1)

tensor([[1., 2., 3., 4.]])

In [16]:
print(f"x2 : \n\n {x2}\n")
print(f"x2 transposed : \n\n {x2.t()}") # transpose

x2 : 

 tensor([[10., 20., 30.],
        [40., 50., 60.]])

x2 transposed : 

 tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])


In [24]:
torch.cat([x1, x2], dim=1) # 행렬을 묶는 method

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [32]:
hwc_img_data = torch.rand(100, 64, 32 ,3)
hwc_img_data.shape

torch.Size([100, 64, 32, 3])

In [33]:
chw_img_data = hwc_img_data.transpose(1, 2) # 1 차원과 2차원을 교환  BHWC -> BWHC

In [34]:
chw_img_data = chw_img_data.transpose(1, 3) # 1 차원과 3차원의 값들을 교환 BWHC -> BCHW
chw_img_data.size()

torch.Size([100, 3, 64, 32])