<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/d_Concat(JoinCompute).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# concatenate 연산
- dim : concatenate할 방향(축)을 정할 수 있다.

In [3]:
x = torch.cuda.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.cuda.FloatTensor([[-1, -2, -3], [-4, -5, -6]])

In [4]:
z1 = torch.cat([x, y], dim=0)
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]], device='cuda:0')

In [5]:
z2 = torch.cat([x, y], dim=1)
z2

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]], device='cuda:0')

- stack을 통해서도 concatenate할 수 있다.

In [7]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x_stack = torch.stack([x, x, x, x], dim=0) # stack은 새로운 차원축을 따라서 stack한다. ((2, 2)들을 stack -> (1, 2, 2))
x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

In [10]:
b, h, w = x_stack.size()
print(x_stack.size())
print(b, h, w)

torch.Size([4, 2, 3])
4 2 3
