<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/Pytorch_Tips_Details/e_Initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 초기화 방법

In [2]:
import torch.nn.init as init

In [4]:
x1 = init.uniform(torch.FloatTensor(3, 4), a = 0, b = 9) # uniform 분포의 초기화 Tensor
x1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """Entry point for launching an IPython kernel.


tensor([[4.3527, 8.8881, 1.3414, 4.8993],
        [5.0518, 8.8734, 1.3343, 4.9315],
        [1.8337, 1.6046, 3.8145, 3.9976]])

In [6]:
x2 = init.normal(torch.FloatTensor(3, 4), std=0.2) # noraml 분포의 초기화 Tensor
x2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  """Entry point for launching an IPython kernel.


tensor([[ 0.1216,  0.0503, -0.4610,  0.2245],
        [ 0.2337,  0.1919,  0.2615, -0.0361],
        [ 0.0395,  0.0029,  0.1707,  0.1788]])

In [7]:
x3 = init.constant(torch.FloatTensor(3, 4), 3.1415) # 상수형태로 초기화
x3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """Entry point for launching an IPython kernel.


tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]])