<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/f_MathOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 벡터 내적

In [2]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).view(3, 2)
b = torch.tensor([9, 8, 7, 6, 5, 4]).view(2, 3)
ab = torch.matmul(a, b)
ab

tensor([[21, 18, 15],
        [51, 44, 37],
        [81, 70, 59]])

In [3]:
ab = a@b
ab

tensor([[21, 18, 15],
        [51, 44, 37],
        [81, 70, 59]])

# + 연산 방법

In [4]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
add = x1 + x2
add

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [5]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]]) # 
x1 + 10 # broadcasting

tensor([[11., 12., 13.],
        [14., 15., 16.]])

# * 연산 방법

In [7]:
x1 = torch.FloatTensor([[1, 2, 3], [4 , 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4 , 5, 6]])
x1 * x2 # elementwise, (torch.mul(x1, x2))

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

# / 연산 방법

In [9]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1/x2 # elementwise, (torch.div(x1, x2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1 / 5 #broadcasting

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

# Pow 연산

In [11]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1 ** 2 # torch.pow(input, exponent)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

# Exponential 연산

In [12]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
torch.exp(x1)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

# Log 연산

In [22]:
import math
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, math.exp(1)]])
torch.log(x1)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.0000]])

# Matrix Multiplication
- shape이 잘 맞아야 연산된다.

In [23]:
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
torch.mm(x1, x2).size()

torch.Size([3, 5])

- Tensor 곱을 Batch 단위로 처리한다.
- torch.mm은 단일 텐서, 즉 행렬로 계산을 한 것이다.
- batch 단위로 처리하면 효율적인 경우가 있다.

In [24]:
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
torch.bmm(x1, x2).size()

torch.Size([10, 3, 5])

# Matrix Dot

In [26]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1])) # 두 텐서의 dot product을 수행

tensor(7)

# Matrix transposed

In [28]:
x1 = torch.FloatTensor(2, 3)
x1

tensor([[2.6737e+36, 3.0611e-41, 3.3631e-44],
        [0.0000e+00,        nan, 1.9233e+00]])

In [29]:
x2 = x1.t() # transposed tensor

In [34]:
x1 = torch.FloatTensor(10, 3, 4, 5)
x1.size()
torch.transpose(x1, 1, 2).size() # 특정 dimension을 변경할 수 있다.

torch.Size([10, 4, 3, 5])

In [35]:
torch.transpose(x1, 2, 3).size()

torch.Size([10, 3, 5, 4])

# eigenvalue, eigenvector

In [37]:
x1 = torch.FloatTensor(4, 4)
torch.eig(x1, eigenvectors=True)

torch.return_types.eig(eigenvalues=tensor([[0.0000e+00, 0.0000e+00],
        [2.6739e+36, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]]), eigenvectors=tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.0252e-37,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0150e-15],
        [ 1.0000e+00,  1.0526e-13, -1.0000e+00, -1.0000e+00]]))