<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/f_MathOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 벡터 내적

In [2]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).view(3, 2)
b = torch.tensor([9, 8, 7, 6, 5, 4]).view(2, 3)
ab = torch.matmul(a, b)
ab

tensor([[21, 18, 15],
        [51, 44, 37],
        [81, 70, 59]])

In [3]:
ab = a@b
ab

tensor([[21, 18, 15],
        [51, 44, 37],
        [81, 70, 59]])

# + 연산 방법

In [4]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
add = x1 + x2
add

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [5]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]]) # 
x1 + 10 # broadcasting

tensor([[11., 12., 13.],
        [14., 15., 16.]])

# * 연산 방법

In [6]:
x1 = torch.FloatTensor([[1, 2, 3], [4 , 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4 , 5, 6]])
x1 * x2 # elementwise, (torch.mul(x1, x2))

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

# / 연산 방법

In [7]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1/x2 # elementwise, (torch.div(x1, x2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1 / 5 #broadcasting

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

# Pow 연산

In [9]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1 ** 2 # torch.pow(input, exponent)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

# Exponential 연산

In [10]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
torch.exp(x1)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

# Log 연산

In [11]:
import math
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, math.exp(1)]])
torch.log(x1)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.0000]])

# Matrix Multiplication
- shape이 잘 맞아야 연산된다.

In [12]:
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
torch.mm(x1, x2).size()

torch.Size([3, 5])

- Tensor 곱을 Batch 단위로 처리한다.
- torch.mm은 단일 텐서, 즉 행렬로 계산을 한 것이다.
- batch 단위로 처리하면 효율적인 경우가 있다.

In [13]:
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
torch.bmm(x1, x2).size()

torch.Size([10, 3, 5])

# Matrix Dot

In [14]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1])) # 두 텐서의 dot product을 수행

tensor(7)

# Matrix transposed

In [15]:
x1 = torch.FloatTensor(2, 3)
x1

tensor([[       nan, 3.0806e-41, 4.2039e-45],
        [0.0000e+00,        nan, 0.0000e+00]])

In [16]:
x2 = x1.t() # transposed tensor

In [17]:
x1 = torch.FloatTensor(10, 3, 4, 5)
x1.size()
torch.transpose(x1, 1, 2).size() # 특정 dimension을 변경할 수 있다.

torch.Size([10, 4, 3, 5])

In [18]:
torch.transpose(x1, 2, 3).size()

torch.Size([10, 3, 5, 4])

# eigenvalue, eigenvector

In [29]:
x1 = torch.FloatTensor(4,4) # nan이 나올 때도 있다 ㅋ
torch.eig(x1, eigenvectors=True)

RuntimeError: ignored

# einsum
![image](https://user-images.githubusercontent.com/69780812/140712360-8d794571-32be-4756-9b78-75ac12b50611.png)


In [31]:
x = torch.rand((2, 3))
x.shape

torch.Size([2, 3])

In [33]:
# Permutation
x2 = torch.einsum("ij->ji", x)
print(x2)
print(x2.shape)

tensor([[0.1282, 0.9306],
        [0.6292, 0.5559],
        [0.2000, 0.6452]])
torch.Size([3, 2])


In [34]:
# Summation
x3 = torch.einsum("ij->", x)
print(x3)
print(x3.shape)

tensor(3.0892)
torch.Size([])


In [35]:
# column sum
x4 = torch.einsum("ij->j", x)
print(x4)
print(x4.shape)

tensor([1.0588, 1.1851, 0.8453])
torch.Size([3])


In [36]:
# row sum
x5 = torch.einsum("ij->i", x)
print(x5)
print(x5.shape)

tensor([0.9574, 2.1318])
torch.Size([2])


In [55]:
# matrix vector multiplication
x = torch.randint(low=1, high=10, size=(2, 3)) # matrix
v = torch.randint(low=1, high=10, size=(1, 3)) # row voctor
x6 = torch.einsum("ij,kj->ik", x, v)
print(x)
print(v)
print(x6)
print(x6.shape)

# 여러 시도를 해보니
# 좌변 우변에 겹쳐있는 알파벳끼리 요소별 곱이고
# 우변에서 사라지는 변수의 차원을 따라 합하면된다.

tensor([[4, 2, 5],
        [3, 3, 6]])
tensor([[7, 5, 7]])
tensor([[73],
        [78]])
torch.Size([2, 1])
