<a href="https://colab.research.google.com/github/ChaejinE/MyPytorch/blob/main/PyTorch_Tips_Details/m_argmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

- argmax의 return 값은 차원 방향의 인덱스다.

In [2]:
A = torch.randint(10, (3, 4, 2))
A

tensor([[[0, 4],
         [1, 7],
         [5, 0],
         [9, 6]],

        [[8, 6],
         [3, 3],
         [9, 6],
         [3, 7]],

        [[2, 1],
         [6, 5],
         [7, 4],
         [1, 0]]])

In [3]:
torch.argmax(A, dim=0)

tensor([[1, 1],
        [2, 0],
        [1, 1],
        [0, 1]])

In [4]:
torch.argmax(A, dim=1)

tensor([[3, 1],
        [2, 3],
        [2, 1]])

In [5]:
torch.argmax(A, dim=2)

tensor([[1, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]])